/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    brands: Brand;
    media: Media;
    products: Product;
    productVariants: ProductVariant;
    orders: Order;
    orderItems: OrderItem;
    customers: Customer;
    payouts: Payout;
    collections: Collection;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    productVariants: ProductVariantsSelect<false> | ProductVariantsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    orderItems: OrderItemsSelect<false> | OrderItemsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    payouts: PayoutsSelect<false> | PayoutsSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    commerceSettings: CommerceSetting;
  };
  globalsSelect: {
    commerceSettings: CommerceSettingsSelect<false> | CommerceSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * User role determines access level
   */
  role: 'admin' | 'brandOwner' | 'brandStaff' | 'support';
  /**
   * The brand this user belongs to (required for brand users)
   */
  brand?: (number | null) | Brand;
  firstName?: string | null;
  lastName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  /**
   * Brand name as shown to customers
   */
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Square logo, monochrome recommended
   */
  logo?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  /**
   * Brief introduction to the brand
   */
  shortDescription?: string | null;
  /**
   * Full brand story and details
   */
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Who this brand is for (e.g., "For the design-obsessed homebody")
   */
  giftFit?: string | null;
  /**
   * Style and vibe of the brand
   */
  styleTags?: ('minimal' | 'cozy' | 'playful' | 'luxurious' | 'bold' | 'earthy' | 'modern' | 'classic')[] | null;
  country: 'GB' | 'US' | 'FR' | 'DE' | 'OTHER';
  baseCurrency: 'GBP' | 'USD' | 'EUR';
  websiteUrl?: string | null;
  instagramHandle?: string | null;
  otherSocials?:
    | {
        platform?: ('twitter' | 'tiktok' | 'pinterest') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Brand approval status
   */
  status: 'pending' | 'approved' | 'rejected' | 'suspended';
  /**
   * Internal notes for admin team only
   */
  internalNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  /**
   * Stripe Connect account ID
   */
  stripeConnectAccountId?: string | null;
  stripeOnboardingStatus?: ('not_started' | 'in_progress' | 'complete') | null;
  /**
   * Override platform fee for this brand (optional)
   */
  defaultPlatformFeePercent?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Auto-generated from title
   */
  slug: string;
  /**
   * The brand that owns this product
   */
  brand: number | Brand;
  status: 'draft' | 'published' | 'archived';
  /**
   * Short description appears first. Think of it as how I introduce the product in a sentence.
   */
  shortDescription?: string | null;
  /**
   * Full product description with details
   */
  description?: string | null;
  /**
   * Technical specifications or product details
   */
  specs?: string | null;
  /**
   * Main product image
   */
  primaryImage: number | Media;
  /**
   * Clear, editorial photography helps me present you well inside Gifter.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Tags like "For the ritualist", "For the host", "Under £50", etc.
   */
  giftTags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Which occasions is this product suitable for?
   */
  occasionFit?:
    | ('birthday' | 'anniversary' | 'housewarming' | 'thankyou' | 'justbecause' | 'wedding' | 'babyshower')[]
    | null;
  /**
   * These help me understand who this is for. I use them when lining up recommendations.
   */
  styleTags?: ('minimal' | 'bold' | 'cozy' | 'luxurious' | 'playful' | 'earthy' | 'modern' | 'classic')[] | null;
  /**
   * Does this product have variants (e.g., sizes, colors)?
   */
  hasVariants?: boolean | null;
  /**
   * Base price (or only price if no variants)
   */
  defaultPrice?: number | null;
  defaultCurrency?: ('GBP' | 'USD' | 'EUR') | null;
  /**
   * SKU (if no variants)
   */
  defaultSku?: string | null;
  /**
   * Stock quantity (if no variants)
   */
  defaultStock?: number | null;
  /**
   * Featured products may appear in curated collections
   */
  isFeatured?: boolean | null;
  /**
   * Is this product available to Gifter app users?
   */
  visibleToGifter?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productVariants".
 */
export interface ProductVariant {
  id: number;
  /**
   * The parent product
   */
  product: number | Product;
  /**
   * Variant options (e.g., Size: M, Color: Black)
   */
  optionValues: {
    /**
     * Option name (e.g., "Size", "Color")
     */
    option: string;
    /**
     * Option value (e.g., "M", "Black")
     */
    value: string;
    id?: string | null;
  }[];
  /**
   * Stock keeping unit / variant code
   */
  sku: string;
  price: number;
  currency: 'GBP' | 'USD' | 'EUR';
  /**
   * Available stock for this variant (leave empty for external inventory)
   */
  stock?: number | null;
  /**
   * Stripe Price ID for this variant
   */
  stripePriceId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Unique order identifier
   */
  orderNumber: string;
  brand: number | Brand;
  customer?: (number | null) | Customer;
  /**
   * User ID from Core Gifter API (Prisma)
   */
  coreUserId?: string | null;
  /**
   * Occasion ID from Core Gifter API (Prisma)
   */
  coreOccasionId?: string | null;
  currency: 'GBP' | 'USD' | 'EUR';
  /**
   * Subtotal before shipping and tax
   */
  subtotal: number;
  shipping?: number | null;
  tax?: number | null;
  /**
   * Final total amount
   */
  total: number;
  status: 'pending' | 'paid' | 'fulfilled' | 'cancelled' | 'refunded';
  /**
   * When payment was completed
   */
  paidAt?: string | null;
  /**
   * When order was marked as fulfilled
   */
  fulfilledAt?: string | null;
  /**
   * Stripe PaymentIntent ID
   */
  stripePaymentIntentId?: string | null;
  /**
   * Stripe Charge ID
   */
  stripeChargeId?: string | null;
  /**
   * Stripe Transfer ID (if using separate transfers)
   */
  stripeTransferId?: string | null;
  /**
   * Stripe processing fee (for reporting)
   */
  stripeFeeAmount?: number | null;
  /**
   * Platform commission fee
   */
  platformFeeAmount?: number | null;
  shippingAddress?: {
    firstName?: string | null;
    lastName?: string | null;
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  /**
   * Note from the buyer
   */
  buyerNote?: string | null;
  /**
   * Internal notes (brand/admin only)
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * The brand this customer has purchased from
   */
  brand: number | Brand;
  /**
   * Link to Core Gifter user ID (from Prisma DB)
   */
  externalUserId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orderItems".
 */
export interface OrderItem {
  id: number;
  order: number | Order;
  product: number | Product;
  /**
   * Specific variant if applicable
   */
  variant?: (number | null) | ProductVariant;
  quantity: number;
  /**
   * Price per unit at time of order
   */
  unitPrice: number;
  currency: 'GBP' | 'USD' | 'EUR';
  /**
   * quantity × unitPrice
   */
  subtotal: number;
  /**
   * Product title at time of order
   */
  productTitle: string;
  /**
   * Variant description (e.g., "Size: M, Color: Black")
   */
  variantSummary?: string | null;
  /**
   * Brand name at time of order
   */
  brandName?: string | null;
  /**
   * Product image at time of order
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payouts".
 */
export interface Payout {
  id: number;
  brand: number | Brand;
  /**
   * Related order (if applicable)
   */
  order?: (number | null) | Order;
  /**
   * Type of transaction
   */
  type: 'payout' | 'platformFee' | 'refund' | 'adjustment';
  /**
   * Amount (can be negative for fees/refunds)
   */
  amount: number;
  currency: 'GBP' | 'USD' | 'EUR';
  /**
   * Stripe Transfer ID
   */
  stripeTransferId?: string | null;
  /**
   * Stripe Balance Transaction ID
   */
  stripeBalanceTransactionId?: string | null;
  /**
   * Description of this transaction
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  title: string;
  slug: string;
  subtitle?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Manually curated products
   */
  products?:
    | {
        product: number | Product;
        /**
         * Order in which products appear
         */
        sortIndex?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional dynamic filters for collection (JSON)
   */
  filters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  isFeatured?: boolean | null;
  /**
   * Who is this collection for?
   */
  targetPersona?: string | null;
  targetOccasion?:
    | ('birthday' | 'anniversary' | 'housewarming' | 'thankyou' | 'justbecause' | 'wedding' | 'babyshower')[]
    | null;
  /**
   * Hero image for the collection
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'productVariants';
        value: number | ProductVariant;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'orderItems';
        value: number | OrderItem;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'payouts';
        value: number | Payout;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  brand?: T;
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  coverImage?: T;
  shortDescription?: T;
  longDescription?: T;
  giftFit?: T;
  styleTags?: T;
  country?: T;
  baseCurrency?: T;
  websiteUrl?: T;
  instagramHandle?: T;
  otherSocials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  status?: T;
  internalNotes?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  stripeConnectAccountId?: T;
  stripeOnboardingStatus?: T;
  defaultPlatformFeePercent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  brand?: T;
  status?: T;
  shortDescription?: T;
  description?: T;
  specs?: T;
  primaryImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  giftTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  occasionFit?: T;
  styleTags?: T;
  hasVariants?: T;
  defaultPrice?: T;
  defaultCurrency?: T;
  defaultSku?: T;
  defaultStock?: T;
  isFeatured?: T;
  visibleToGifter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productVariants_select".
 */
export interface ProductVariantsSelect<T extends boolean = true> {
  product?: T;
  optionValues?:
    | T
    | {
        option?: T;
        value?: T;
        id?: T;
      };
  sku?: T;
  price?: T;
  currency?: T;
  stock?: T;
  stripePriceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  brand?: T;
  customer?: T;
  coreUserId?: T;
  coreOccasionId?: T;
  currency?: T;
  subtotal?: T;
  shipping?: T;
  tax?: T;
  total?: T;
  status?: T;
  paidAt?: T;
  fulfilledAt?: T;
  stripePaymentIntentId?: T;
  stripeChargeId?: T;
  stripeTransferId?: T;
  stripeFeeAmount?: T;
  platformFeeAmount?: T;
  shippingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  buyerNote?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orderItems_select".
 */
export interface OrderItemsSelect<T extends boolean = true> {
  order?: T;
  product?: T;
  variant?: T;
  quantity?: T;
  unitPrice?: T;
  currency?: T;
  subtotal?: T;
  productTitle?: T;
  variantSummary?: T;
  brandName?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  lastName?: T;
  brand?: T;
  externalUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payouts_select".
 */
export interface PayoutsSelect<T extends boolean = true> {
  brand?: T;
  order?: T;
  type?: T;
  amount?: T;
  currency?: T;
  stripeTransferId?: T;
  stripeBalanceTransactionId?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  description?: T;
  products?:
    | T
    | {
        product?: T;
        sortIndex?: T;
        id?: T;
      };
  filters?: T;
  isFeatured?: T;
  targetPersona?: T;
  targetOccasion?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commerceSettings".
 */
export interface CommerceSetting {
  id: number;
  /**
   * Default platform commission percentage
   */
  platformFeePercent: number;
  supportedCurrencies?: ('GBP' | 'USD' | 'EUR')[] | null;
  allowedCountries?:
    | {
        code: string;
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Stripe publishable key (can be test or live)
   */
  stripePublishableKey?: string | null;
  /**
   * Base URL for Stripe Connect return URL
   */
  returnUrlBase?: string | null;
  /**
   * Base URL for Stripe Connect refresh URL
   */
  refreshUrlBase?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commerceSettings_select".
 */
export interface CommerceSettingsSelect<T extends boolean = true> {
  platformFeePercent?: T;
  supportedCurrencies?: T;
  allowedCountries?:
    | T
    | {
        code?: T;
        name?: T;
        id?: T;
      };
  stripePublishableKey?: T;
  returnUrlBase?: T;
  refreshUrlBase?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}