FROM node:20-alpine AS base

FROM base AS builder
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install turbo globally
RUN npm install -g turbo@^2.3.3

COPY . .

# Prune the workspace for api
RUN turbo prune api --docker

FROM base AS installer
RUN apk add --no-cache libc6-compat
WORKDIR /app

# First install dependencies
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/package-lock.json ./package-lock.json

RUN npm ci

# Build the project
COPY --from=builder /app/out/full/ .
RUN npx turbo run build --filter=api...

# Generate Prisma Client specifically for api
WORKDIR /app/apps/api
RUN npx prisma generate

FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
ENV PORT 4000

# We copy the entire pruned tree which includes the built files and node_modules
COPY --from=installer /app .

WORKDIR /app/apps/api

EXPOSE 4000

# Start the API
CMD ["npm", "run", "start"]
